import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased h-screen`}
      >
        <div className=" pb-16 mx-auto sm:min-w-sm md:max-w-3xl">
          {/* Content */}
          <main>{children}</main>

          <hr className="mx-4 mt-8 mb-4 border-pink-300" />
          {/* Navbar */}
          <Navbar />

          {/* Footer */}
          <Footer />
        </div>
      </body>
    </html>
  );
}
